Repository botpress/botpress, pull requests merged in 2018-11, with the labels that each got.

#1098 chore: add sdk readme
  .gitignore
  README.md
  build/gulp.core.js
  docs/reference/README.md
Labels: botpress-server

#1094 chore: edit bot info and improve http error handling
  build/jsonschemas.js
  src/bp/bootstrap.ts
  src/bp/common/editions.ts
  src/bp/core/errors.ts
  src/bp/core/routers/admin/teams.ts
  src/bp/core/routers/admin/users.ts
  src/bp/core/routers/errors.ts
  src/bp/core/routers/modules.ts
  src/bp/core/routers/util.ts
  src/bp/core/server.ts
  src/bp/core/services/admin/community.ts
  src/bp/core/services/admin/errors.ts
  src/bp/core/services/admin/service.ts
  src/bp/core/services/auth/errors.ts
  src/bp/core/services/ghost/service.ts
  src/bp/ui-admin/src/Pages/Teams/Bots.js
  src/bp/ui-admin/src/api.js
  src/bp/ui-admin/src/index.css
  src/bp/ui-admin/src/index.scss
  src/bp/vanilla/bot.config.schema.json
Labels: v11.x

#1099 fix(messenger): add subscribed_fields required field
  packages/channels/botpress-channel-messenger/src/messenger.js
Labels: v10.x

#1125 fix(qna): add bom-symbol to exported csv
  packages/functionals/botpress-qna/src/index.js
Labels: v10.x

#1130 Dot env to gitignore
  packages/core/botpress/src/cli/templates/init-default/.gitignore
Labels: v10.x
