Repository botpress/botpress, pull requests merged in 2018-12, with the labels that each got.

#1188 fix(webchat): redundant jumps to the bottom of the chat
  packages/channels/botpress-channel-web/package.json
  packages/channels/botpress-channel-web/src/views/web/messages/carousel.jsx
  packages/channels/botpress-channel-web/src/views/web/messages/index.jsx
  packages/channels/botpress-channel-web/yarn.lock
Labels: v10.x

#1172 fix(core): remove unused module import
  packages/core/botpress/src/web/lite.jsx
Labels: v10.x

#1146 Add platform to id so that users.tag() works
  packages/channels/botpress-channel-messenger/src/users.js
Labels: v10.x

#1215 Added Recast NLU example
  docs/guide/docs/build/code.md
  docs/guide/docs/build/nlu.md
  modules/builtin/src/hooks/before_incoming_middleware/.05_recast_nlu.js
  modules/nlu/src/backend/middleware.ts
  src/bp/core/sdk/enums.ts
  src/bp/core/services/action/action-service.ts
  src/bp/core/services/hook/hook-service.ts
  src/bp/sdk/botpress.d.ts
Labels: v11.x

#1226 entity as crf feature + refactor + fixed some entity bugs at the same time
  modules/nlu/src/backend/engine.ts
  modules/nlu/src/backend/pipelines/entities/duckling_extractor.ts
  modules/nlu/src/backend/pipelines/entities/pattern_extractor.test.ts
  modules/nlu/src/backend/pipelines/entities/pattern_extractor.ts
  modules/nlu/src/backend/pipelines/slots/crf_extractor.ts
  modules/nlu/src/backend/pipelines/slots/pre-processor.test.ts
  modules/nlu/src/backend/pipelines/slots/pre-processor.ts
  modules/nlu/src/backend/pipelines/slots/tagger.ts
  modules/nlu/src/backend/typings.ts
Labels: v11.x

#1219 feat(qna): revamp ui and add answer variations
  modules/qna/package.json
  modules/qna/src/backend/api.ts
  modules/qna/src/backend/setup.ts
  modules/qna/src/views/FormControlIme.jsx
  modules/qna/src/views/FormModal.jsx
  modules/qna/src/views/button.css
  modules/qna/src/views/index.jsx
  modules/qna/src/views/style.scss
  src/bp/core/services/dialog/engine.ts
  src/bp/ui-studio/src/web/components/Shared/ElementsList/InputElement.jsx
  src/bp/ui-studio/src/web/components/Shared/ElementsList/index.jsx
  src/bp/ui-studio/src/web/components/Shared/ElementsList/style.scss
  src/bp/ui-studio/src/web/index.jsx
Labels: v11.x

#1246 fix(webchat): loading webchat-extensions (resolve #1183)
  packages/channels/botpress-channel-web/src/views/web/messages/index.jsx
Labels: v10.x

#1237 fix(nlu): improve error-logs for RASA NLU module (ref #1227, ref #1070)
  packages/functionals/botpress-nlu/src/providers/rasa.js
Labels: v10.x

#1236 fix(webchat): move webchatUrlQuery to event.raw.data (ref #721)
  packages/channels/botpress-channel-web/README.md
  packages/channels/botpress-channel-web/src/api.js
  packages/channels/botpress-channel-web/src/views/web/index.jsx
  packages/core/botpress/src/web/lite.jsx
Labels: v10.x

#1250 fix(docs): try fixing links in tutorial (ref #1235)
  docs/guide/docs/tutorials.md
  docs/guide/website/versioned_docs/version-11.0.1/tutorials.md
Labels: type/documentation

#1259 Avoid knex warning during migration
  packages/core/botpress/migrations/003-ghost_content-file_folder_uniq_index.js
Labels: v10.x

#1260 fix(core): upgrade nodemon to fix event-stream issue
  packages/core/botpress/package.json
  packages/core/botpress/yarn.lock
Labels: v10.x

#1261 fix(webchat): fix iframe overlaying menu (resolve #1251)
  packages/channels/botpress-channel-web/src/views/web/index.jsx
Labels: v10.x

#1263 fix(builtins): syntax error in renderers (resolve #1262)
  packages/core/botpress-builtins/src/renderers/builtin_action-button.js
Labels: v10.x
