Repository botpress/botpress, pull requests merged in 2019-01, with the labels that each got.

#1265 Update README.md
  README.md
Labels: type/documentation

#1272 added possibility to switch hor/ver and hide/show inspector
  src/bp/core/services/converse.ts
  src/bp/ui-studio/src/web/components/ChatEmulator/Emulator.jsx
  src/bp/ui-studio/src/web/components/ChatEmulator/Emulator.styl
Labels: merge/ready

#1274 Ya minor fixes
  modules/builtin/src/bot-templates/small-talk/flows/main.ui.json
  modules/nlu/src/views/entities/SidePanel.jsx
  src/bp/ui-studio/src/web/keyboardShortcuts.js
Labels: merge/ready

#1284 fix(telegram): proper lru-cache initialization (resolve #1240)
  packages/channels/botpress-channel-telegram/src/incoming.js
Labels: v10.x

#1285 fix(builtins): add missing raw-renderer (resolve #1169)
  packages/core/botpress-builtins/src/renderers/builtin_raw.js
  packages/core/botpress-builtins/src/renderers/index.js
Labels: v10.x

#1254 chore: strip flow name from analytics
  src/bp/ui-studio/src/web/components/Routes/index.jsx
Labels: merge/ready

#1334 fix(nlu): logs on EPIPE error + instructions on fixing it
  modules/nlu/README.md
  modules/nlu/src/backend/pipelines/slots/crf_extractor.ts
  modules/nlu/src/backend/tools/fastText.ts
  src/bp/core/services/module/config-reader.ts
Labels: v11.x
