Repository botpress/botpress, pull requests merged in 2020-06, with the labels that each got.

#3348 feat(qna): content form
  modules/builtin/src/content-types/card.js
  modules/builtin/src/content-types/carousel.js
  modules/builtin/src/content-types/image.js
  modules/builtin/src/content-types/single_choice.js
  modules/builtin/src/translations/en.json
  modules/builtin/src/translations/fr.json
  modules/qna/src/backend/qna.d.ts
  modules/qna/src/backend/validation.ts
  modules/qna/src/translations/en.json
  modules/qna/src/translations/fr.json
  modules/qna/src/views/full/Components/ContentAnswer/index.tsx
  modules/qna/src/views/full/Components/ContentAnswer/style.scss
  modules/qna/src/views/full/Components/ContentAnswer/style.scss.d.ts
  modules/qna/src/views/full/Components/ContentAnswerForm/index.tsx
  modules/qna/src/views/full/Components/ContentAnswerForm/style.scss
  modules/qna/src/views/full/Components/ContentAnswerForm/style.scss.d.ts
  modules/qna/src/views/full/Components/QnA.tsx
  modules/qna/src/views/full/Components/TextAreaList.tsx
  modules/qna/src/views/full/style.scss
  modules/qna/src/views/full/style.scss.d.ts
  modules/qna/src/views/full/utils/qnaList.utils.ts
  src/bp/common/typings.ts
  src/bp/core/routers/bots/content.ts
  src/bp/sdk/botpress.d.ts
  src/bp/ui-shared/src/ContentForms/Components/FieldWrapper.tsx
  src/bp/ui-shared/src/ContentForms/Components/Fields/AddButton.tsx
  src/bp/ui-shared/src/ContentForms/Components/Fields/Select.tsx
  src/bp/ui-shared/src/ContentForms/Components/Fields/Text.tsx
  src/bp/ui-shared/src/ContentForms/Components/Fields/TextArea.tsx
  src/bp/ui-shared/src/ContentForms/Components/Fields/Upload.tsx
  src/bp/ui-shared/src/ContentForms/Components/Form/index.tsx
  src/bp/ui-shared/src/ContentForms/Components/Form/style.scss
  src/bp/ui-shared/src/ContentForms/Components/Form/style.scss.d.ts
  src/bp/ui-shared/src/ContentForms/Components/Form/typings.d.ts
  src/bp/ui-shared/src/ContentForms/Components/GroupItemWrapper.tsx
  src/bp/ui-shared/src/ContentForms/Components/style.scss
  src/bp/ui-shared/src/ContentForms/Components/style.scss.d.ts
  src/bp/ui-shared/src/ContentForms/Components/typings.d.ts
  src/bp/ui-shared/src/ContentForms/index.tsx
  src/bp/ui-shared/src/ContentForms/utils/fields.ts
  src/bp/ui-shared/src/ContentForms/utils/typings.d.ts
  src/bp/ui-shared/src/Dropdown/index.tsx
  src/bp/ui-shared/src/FormFields/index.tsx
  src/bp/ui-shared/src/MainContent/Header/index.tsx
  src/bp/ui-shared/src/MainContent/RightSidebar/index.tsx
  src/bp/ui-shared/src/MainContent/RightSidebar/style.scss
  src/bp/ui-shared/src/MainContent/RightSidebar/style.scss.d.ts
  src/bp/ui-shared/src/MainContent/RightSidebar/typings.ts
  src/bp/ui-shared/src/MainContent/Wrapper/index.tsx
  src/bp/ui-shared/src/MainContent/Wrapper/style.scss
  src/bp/ui-shared/src/MainContent/Wrapper/style.scss.d.ts
  src/bp/ui-shared/src/Textarea/typings.d.ts
  src/bp/ui-shared/src/index.tsx
  src/bp/ui-shared/src/translations/en.json
  src/bp/ui-shared/src/translations/fr.json
  src/bp/ui-shared/src/typings.d.ts
Labels: release/12.11.0

#3411 feat(core): base for variables
  api.rest
  modules/builtin/src/backend/index.ts
  modules/builtin/src/backend/variables/boolean.ts
  modules/builtin/src/backend/variables/date.ts
  modules/builtin/src/backend/variables/number.ts
  modules/builtin/src/backend/variables/string.ts
  modules/builtin/src/translations/en.json
  modules/builtin/src/translations/fr.json
  modules/nlu/src/backend/tools/math.ts
  src/bp/common/action.ts
  src/bp/core/api.ts
  src/bp/core/botpress.ts
  src/bp/core/misc/templating.ts
  src/bp/core/module-loader.ts
  src/bp/core/routers/modules.ts
  src/bp/core/services/action/action-service.ts
  src/bp/core/services/auth-strategies.ts
  src/bp/core/services/cms.ts
  src/bp/core/services/dialog/dialog-engine.ts
  src/bp/core/services/dialog/instruction/strategy.ts
  src/bp/core/services/middleware/state-manager.ts
  src/bp/sdk/botpress.d.ts
Labels: merge/wait

#3413 fix(qna): various bugfixes for release
  modules/qna/src/backend/qna.d.ts
  modules/qna/src/views/full/Components/ContextSelector.tsx
  modules/qna/src/views/full/Components/QnA.tsx
  modules/qna/src/views/full/index.tsx
  modules/qna/src/views/full/style.scss
  modules/qna/src/views/full/style.scss.d.ts
  modules/qna/src/views/full/utils/qnaList.utils.ts
Labels: minor/12.10.0

#3407 fix(analytics): fix nan display
  modules/analytics/src/views/full/RadialMetric.tsx
  modules/analytics/src/views/full/index.tsx
  modules/analytics/src/views/full/utils.ts
Labels: minor/12.10.0

#3406 fix(studio): flow / oneflow path
  src/bp/ui-studio/src/web/components/Layout/CommandPalette.tsx
  src/bp/ui-studio/src/web/views/Content/UsageModal.tsx
  src/bp/ui-studio/src/web/views/FlowBuilder/diagram/nodes/Ports.tsx
Labels: minor/12.10.0

#3372 fix(nlu): remove sensitive data
  modules/nlu/src/backend/entities/custom-entity-extractor.ts
  modules/nlu/src/backend/entities/list-extractor.test.ts
  modules/nlu/src/backend/module-lifecycle/on-server-started.ts
  modules/nlu/src/backend/predict-pipeline.ts
  modules/nlu/src/backend/typings.ts
  src/bp/sdk/botpress.d.ts
Labels: minor/12.10.0

#3396 fix(core): say something was not using templates properly
  src/bp/core/services/cms.ts
Labels: minor/12.10.0

#3405 fix(core): clear workflow property before assigning
  src/bp/core/services/middleware/state-manager.ts
Labels: minor/12.10.0

#3416 chore(mltoolkit): new fasttext bindings using Napi
  build/native-extensions/darwin/all/fasttext.node
  build/native-extensions/linux/centos_7_5/fasttext.node
  build/native-extensions/linux/debian_8_11/fasttext.node
  build/native-extensions/linux/red-hat_7_5/fasttext.node
  build/native-extensions/linux/ubuntu_16_04/fasttext.node
  build/native-extensions/linux/ubuntu_18_04/fasttext.node
  build/native-extensions/windows/all/fasttext.node
Labels: release/12.11.0
