Repository botpress/botpress, pull requests merged in 2021-03, with the labels that each got.

#4570 fix(hitl2): fixed agent rules
  modules/hitlnext/src/backend/workspace.ts
  src/bp/migrations/v12_18_1-1614716851-fixed_agent_role_rules.ts
Labels: module/hitlnext(beta)

#4530 feat(core): better migration management
  .github/workflows/code/test-migrations/index.js
  .github/workflows/migration-tests.yml
  .github/workflows/tests.yml
  build/gulp.core.js
  build/gulp.migration.js
  gulpfile.js
  modules/code-editor/src/views/full/components/FileStatus.tsx
  src/bp/core/services/bot-service.ts
  src/bp/core/services/migration/bot.ts
  src/bp/core/services/migration/index.ts
  src/bp/index.ts
  src/bp/jest-before.ts
  src/bp/migrations/v12_17_1-1611946378-implement_token_version.ts
  src/bp/sdk/botpress.d.ts
  src/bp/ui-shared/src/MainLayout/BottomPanel/index.tsx
  src/bp/ui-shared/src/MainLayout/index.tsx
  src/typings/global.d.ts
Labels: core/configuration, infrastructure

#4555 fix(core): changed dialog_sessions PK column size
  src/bp/core/database/tables/bot-specific/dialog_sessions.ts
  src/bp/migrations/v12_17_2-1612973566-add_botid_to_dialog_sessions_id_and_remove_botid_column.ts
  src/bp/migrations/v12_18_1-1614560297-change_dialog_sessions_id_column_type.ts
Labels: core/database, core/dialog

#4587 docs(getting started): new introduction text
  docs/guide/docs/introduction.md
Labels: documentation

#4556 docs(infrastructure): table of contents restructure
  docs/guide/docs/infrastructure/cluster.md
  docs/guide/docs/infrastructure/database.md
  docs/guide/docs/infrastructure/databases.md
  docs/guide/docs/infrastructure/deploying.md
  docs/guide/docs/infrastructure/hosting.md
  docs/guide/docs/infrastructure/performances.md
  docs/guide/docs/infrastructure/pipeline.md
  docs/guide/docs/infrastructure/versions.md
  docs/guide/website/sidebars.json
Labels: documentation

#4591 chore(core): group collaborators features together
  src/bp/core/collaborators/repositories/strategy_users.ts
  src/bp/core/collaborators/repositories/workspace_users.ts
  src/bp/core/collaborators/tables/strategy_users.ts
  src/bp/core/collaborators/tables/workspace_users.ts
  src/bp/core/database/tables/server-wide/index.ts
  src/bp/core/repositories/repositories.inversify.ts
  src/bp/core/services/auth/auth-service.ts
  src/bp/core/services/workspace-service.ts
  src/bp/migrations/v12_0_0-1560882898-move_users_to_db.ts
Labels: javascript

#4590 chore(core): refactor events to bring related code together
  src/bp/core/api.ts
  src/bp/core/app.inversify.ts
  src/bp/core/botpress.ts
  src/bp/core/database/tables/bot-specific/index.ts
  src/bp/core/events/event-collector.ts
  src/bp/core/events/event-engine.ts
  src/bp/core/events/event-repository.ts
  src/bp/core/events/event-table.ts
  src/bp/core/events/middleware-chain.test.ts
  src/bp/core/events/middleware-chain.ts
  src/bp/core/events/queue/index.ts
  src/bp/core/events/queue/memory-queue.test.ts
  src/bp/core/events/queue/memory-queue.ts
  src/bp/core/logger/logger.ts
  src/bp/core/repositories/index.ts
  src/bp/core/services/action/action-service.ts
  src/bp/core/services/auth/auth-service.ts
  src/bp/core/services/converse.ts
  src/bp/core/services/dialog/decision-engine.ts
  src/bp/core/services/dialog/dialog-engine.ts
  src/bp/core/services/dialog/instruction/strategy.ts
  src/bp/core/services/hook/hook-service.ts
  src/bp/core/services/messaging/messages.ts
  src/bp/core/services/services.inversify.ts
Labels: javascript

#4593 chore(core): group logger features together
  src/bp/bootstrap.ts
  src/bp/core/app.ts
  src/bp/core/botpress.ts
  src/bp/core/database/index.tests.ts
  src/bp/core/database/tables/bot-specific/index.ts
  src/bp/core/logger/index.ts
  src/bp/core/logger/logs-janitor.ts
  src/bp/core/logger/logs-repository.ts
  src/bp/core/logger/logs-service.ts
  src/bp/core/logger/logs-table.ts
  src/bp/core/logger/persister/console-logger.ts
  src/bp/core/logger/persister/db-persister.ts
  src/bp/core/logger/persister/file-persister.ts
  src/bp/core/logger/utils.ts
  src/bp/core/repositories/repositories.inversify.ts
  src/bp/core/routers/admin/index.ts
  src/bp/core/routers/bots/index.ts
  src/bp/core/server.ts
  src/bp/core/services/bot-monitoring-service.ts
  src/bp/core/services/cms.ts
  src/bp/core/services/migration/bot.ts
  src/bp/core/services/migration/index.ts
  src/bp/core/services/services.inversify.ts
  src/bp/diag/utils.ts
  src/bp/lang-server/index.ts
  src/bp/nlu-server/index.ts
Labels: javascript

#4606 fix(misunderstood): Small UI fix
  modules/misunderstood/src/translations/en.json
  modules/misunderstood/src/translations/es.json
  modules/misunderstood/src/translations/fr.json
  modules/misunderstood/src/views/full/MainScreen/AmendForm.tsx
Labels: X-Games

#4607 fix(analytics): wrong count of misunderstood messages
  modules/analytics/src/backend/setup.ts
Labels: X-Games

#4609 feat(misunderstood): delete done and ignored
  modules/misunderstood/src/backend/api.ts
  modules/misunderstood/src/backend/db.ts
  modules/misunderstood/src/translations/en.json
  modules/misunderstood/src/translations/es.json
  modules/misunderstood/src/translations/fr.json
  modules/misunderstood/src/views/full/ApiClient.ts
  modules/misunderstood/src/views/full/SideList.tsx
  modules/misunderstood/src/views/full/SidePanel.tsx
  modules/misunderstood/src/views/full/index.tsx
  src/bp/ui-admin/yarn.lock
Labels: X-Games

#4613 fix(analytics): fix duplicate language stats
  modules/analytics/src/views/full/index.tsx
Labels: X-Games

#4402 docs(channels) messenger.md update
  docs/guide/docs/assets/messenger-admin-config.png
  docs/guide/docs/channels/messenger.md
Labels: documentation

#4621 feat(qna): enter add new / Ctrl-entrer go to line
  modules/qna/src/views/full/Components/TextAreaList.tsx
Labels: X-Games

#4623 fix(analytics): Overlapped text in graph & active users
  modules/analytics/src/backend/db.ts
  modules/analytics/src/views/full/TimeSeriesChart.tsx
  modules/analytics/src/views/full/index.tsx
Labels: X-Games

#4624 fix(hitl2): scrollable HandoffList
  modules/hitlnext/src/views/full/app/components/HandoffList.tsx
  modules/hitlnext/src/views/full/style.scss
Labels: X-Games

#4627 fix(hitl2): hidden reply box on livechat render
  modules/hitlnext/src/views/full/style.scss
Labels: X-Games

#4617 fix(nlu): translate system entities
  modules/nlu/src/translations/en.json
  modules/nlu/src/translations/es.json
  modules/nlu/src/translations/fr.json
  modules/nlu/src/views/full/intents/slots/EntitySelector.tsx
Labels: X-Games

#4467 feat(core): render service
  src/bp/core/api.ts
  src/bp/core/botpress.ts
  src/bp/core/events/event-engine.ts
  src/bp/core/services/cms.ts
  src/bp/core/services/render/render.test.ts
  src/bp/core/services/render/render.ts
  src/bp/core/services/services.inversify.ts
  src/bp/core/types.ts
  src/bp/sdk/botpress.d.ts
Labels: core/dialog

#4658 fix(studio): translations
  src/bp/ui-shared/src/translations/en.json
  src/bp/ui-shared/src/translations/es.json
  src/bp/ui-shared/src/translations/fr.json
  src/bp/ui-studio/src/web/translations/es.json
Labels: X-Games

#4704 fix(core): nlu and lang server wrong import path
  src/bp/lang-server/index.ts
  src/bp/nlu-server/index.ts
  src/bp/ui-studio/yarn.lock
Labels: language-server

#4691 fix(docker): fix vulnerability
  build/docker/Dockerfile
Labels: infrastructure

#4702 fix(webchat): browser error on IE11
  src/bp/ui-studio/package.json
  src/bp/ui-studio/webpack.web.js
  src/bp/ui-studio/yarn.lock
Labels: module/channel-web

#4711 fix(analytics): support for postgres
  modules/analytics/src/backend/db.ts
Labels: core/database, module/analytics

#4705 fix(core): fix bp pull/push
  src/bp/bpfs.ts
Labels: infrastructure

#4682 chore(core): backend restructuration: messaging
  src/bp/core/api.ts
  src/bp/core/converse/converse-service.ts
  src/bp/core/database/tables/bot-specific/index.ts
  src/bp/core/database/tables/index.ts
  src/bp/core/messaging/conversation-repository.ts
  src/bp/core/messaging/conversation-service.ts
  src/bp/core/messaging/conversations-table.ts
  src/bp/core/messaging/index.ts
  src/bp/core/messaging/message-repository.ts
  src/bp/core/messaging/message-service.ts
  src/bp/core/messaging/messages-table.ts
  src/bp/core/repositories/repositories.inversify.ts
  src/bp/core/services/services.inversify.ts
Labels: core/backend

#4681 chore(core): backend restructuration: users (collaborators, chat-users)
  src/bp/core/api.ts
  src/bp/core/app.inversify.ts
  src/bp/core/botpress.ts
  src/bp/core/collaborators/index.ts
  src/bp/core/converse/converse-service.ts
  src/bp/core/database/tables/bot-specific/index.ts
  src/bp/core/database/tables/index.ts
  src/bp/core/database/tables/server-wide/index.ts
  src/bp/core/dialog/state-manager.ts
  src/bp/core/messaging/conversation-repository.ts
  src/bp/core/messaging/conversation-service.ts
  src/bp/core/messaging/conversations-table.ts
  src/bp/core/messaging/index.ts
  src/bp/core/messaging/message-repository.ts
  src/bp/core/messaging/message-service.ts
  src/bp/core/messaging/messages-table.ts
  src/bp/core/repositories/index.ts
  src/bp/core/repositories/repositories.inversify.ts
  src/bp/core/services/auth/auth-service.ts
  src/bp/core/services/dialog/janitor.ts
  src/bp/core/services/services.inversify.ts
  src/bp/core/services/workspace-service.ts
  src/bp/core/telemetry/stats/legacy-stats.ts
  src/bp/core/users/chat-users/channel_users-table.ts
  src/bp/core/users/chat-users/chat-users-repository.ts
  src/bp/core/users/chat-users/chat_users-table.ts
  src/bp/core/users/chat-users/index.ts
  src/bp/core/users/collaborators/index.ts
  src/bp/core/users/collaborators/repositories/index.ts
  src/bp/core/users/collaborators/repositories/strategy_users.ts
  src/bp/core/users/collaborators/repositories/workspace_invite_codes.ts
  src/bp/core/users/collaborators/repositories/workspace_users.ts
  src/bp/core/users/collaborators/tables/index.ts
  src/bp/core/users/collaborators/tables/strategy_users.ts
  src/bp/core/users/collaborators/tables/workspace_invite_codes.ts
  src/bp/core/users/collaborators/tables/workspace_users.ts
  src/bp/core/users/data-retention/data-retention-janitor.ts
  src/bp/core/users/data-retention/data-retention-service.ts
  src/bp/core/users/data-retention/data_retention-table.ts
  src/bp/core/users/data-retention/util.ts
  src/bp/core/users/index.ts
  src/bp/core/users/tables.ts
  src/bp/migrations/v12_0_0-1560882898-move_users_to_db.ts
Labels: core/backend

#4679 chore(core): backend restructuration: telemetry
  src/bp/core/app.inversify.ts
  src/bp/core/botpress.ts
  src/bp/core/database/tables/index.ts
  src/bp/core/database/tables/server-wide/index.ts
  src/bp/core/repositories/repositories.inversify.ts
  src/bp/core/server.ts
  src/bp/core/services/services.inversify.ts
  src/bp/core/telemetry/index.ts
  src/bp/core/telemetry/stats-service.ts
  src/bp/core/telemetry/stats/actions-stats.ts
  src/bp/core/telemetry/stats/configs-stats.ts
  src/bp/core/telemetry/stats/hooks-stats.ts
  src/bp/core/telemetry/stats/legacy-stats.ts
  src/bp/core/telemetry/stats/roles-stats.ts
  src/bp/core/telemetry/stats/sdk-stats.ts
  src/bp/core/telemetry/stats/telemetry-stats.ts
  src/bp/core/telemetry/stats/telemetry.inversify.ts
  src/bp/core/telemetry/telemetry-repository.ts
  src/bp/core/telemetry/telemetry-router.ts
  src/bp/core/telemetry/telemetry-table.ts
Labels: core/backend

#4678 chore(core): backend restructuration: config, cms, dialog
  src/bp/core/api.ts
  src/bp/core/app.inversify.ts
  src/bp/core/botpress.ts
  src/bp/core/cms/cms-router.ts
  src/bp/core/cms/cms-service.ts
  src/bp/core/cms/code-sandbox.ts
  src/bp/core/cms/index.ts
  src/bp/core/cms/templating.test.ts
  src/bp/core/cms/templating.ts
  src/bp/core/config/bot.config.ts
  src/bp/core/config/index.ts
  src/bp/core/database/tables/bot-specific/index.ts
  src/bp/core/database/tables/index.ts
  src/bp/core/database/tables/server-wide/index.ts
  src/bp/core/dialog/index.ts
  src/bp/core/dialog/sessions/dialog_sessions-table.ts
  src/bp/core/dialog/sessions/expiry.ts
  src/bp/core/dialog/sessions/index.ts
  src/bp/core/dialog/sessions/session-id-factory.ts
  src/bp/core/dialog/sessions/session-repository.ts
  src/bp/core/dialog/state-manager.ts
  src/bp/core/events/event-collector.ts
  src/bp/core/misc/code-sandbox.ts
  src/bp/core/repositories/index.ts
  src/bp/core/repositories/repositories.inversify.ts
  src/bp/core/routers/bots/index.ts
  src/bp/core/server.ts
  src/bp/core/services/auth/auth-service.ts
  src/bp/core/services/bot-service.ts
  src/bp/core/services/dialog/decision-engine.ts
  src/bp/core/services/dialog/dialog.inversify.ts
  src/bp/core/services/dialog/instruction/strategy.ts
  src/bp/core/services/dialog/janitor.ts
  src/bp/core/services/services.inversify.ts
  src/bp/core/telemetry/index.ts
  src/bp/core/telemetry/stats-service.ts
  src/bp/core/telemetry/stats/actions-stats.ts
  src/bp/core/telemetry/stats/configs-stats.ts
  src/bp/core/telemetry/stats/hooks-stats.ts
  src/bp/core/telemetry/stats/legacy-stats.ts
  src/bp/core/telemetry/stats/roles-stats.ts
  src/bp/core/telemetry/stats/sdk-stats.ts
  src/bp/core/telemetry/stats/telemetry-stats.ts
  src/bp/core/telemetry/stats/telemetry.inversify.ts
  src/bp/core/telemetry/telemetry-repository.ts
  src/bp/core/telemetry/telemetry-router.ts
  src/bp/core/telemetry/telemetry-table.ts
  src/bp/sdk/botpress.d.ts
Labels: core/backend

#4622 fix(analytics): fix react errors
  modules/analytics/src/views/full/ItemsList.tsx
  modules/analytics/src/views/full/index.tsx
Labels: X-Games

#4703 fix(core): change server target from ES6 to ES2019
  .vscode/launch.json
  src/bp/core/config/config-loader.ts
  src/bp/core/telemetry/stats/sdk-stats.ts
  src/tsconfig.json
Labels: core/backend

#4707 chore(channel-web): use web session id in requests for enhanced security
  modules/channel-web/src/backend/api.ts
  modules/channel-web/src/views/lite/core/api.tsx
  modules/channel-web/src/views/lite/core/socket.tsx
  modules/channel-web/src/views/lite/typings.d.ts
  package.json
  src/bp/core/api.ts
  src/bp/core/services/realtime/index.ts
  src/bp/sdk/botpress.d.ts
  src/bp/ui-studio/src/web/typings.d.ts
  src/bp/ui-studio/src/web/util/EventBus.ts
  yarn.lock
Labels: module/channel-web

#4709 docs: fix of broken URLs
  docs/guide/docs/advanced/configuration.md
  docs/guide/docs/advanced/development-pipeline.md
  docs/guide/docs/main/nlu.md
  docs/guide/docs/tutorials/hitl.md
Labels: documentation

#4411 docs(channels): teams.md update
  docs/guide/docs/channels/teams.md
Labels: documentation

#4412 docs(channels): slack.md changes
  docs/guide/docs/channels/slack.md
Labels: documentation

#4731 fix(core): flow service caching on update
  src/bp/core/services/dialog/flow/service.ts
Labels: ui/studio/flow

#4698 chore(nlu): Simplify fl_mod_nlu branch
  modules/nlu/src/backend/application/distributed-training-queue.ts
  modules/nlu/src/backend/application/index.ts
  modules/nlu/src/backend/application/scoped/bot.ts
  modules/nlu/src/backend/application/tests/utils/app.u.test.ts
  modules/nlu/src/backend/application/tests/utils/fake-training-repo.u.test.ts
  modules/nlu/src/backend/application/tests/utils/utils.u.test.ts
  modules/nlu/src/backend/application/training-queue.ts
  modules/nlu/src/backend/application/training-repo.ts
  modules/nlu/src/backend/application/training-service.ts
  modules/nlu/src/backend/application/typings.ts
  modules/nlu/src/backend/bootstrap.ts
  modules/nlu/src/backend/train-repo-router.ts
Labels: core/nlu, module/nlu

#4737 chore(nlu): rm ml git submodules as unused
  .gitignore
  .gitmodules
Labels: core/nlu

#4748 fix(nlu): fix debug and progress logging during training
  src/bp/nlu/engine/engine/intents/oos-intent-classfier.ts
  src/bp/nlu/engine/engine/intents/svm-intent-classifier.ts
  src/bp/nlu/engine/engine/training-pipeline.ts
Labels: core/nlu

#4718 fix(basic-skills): slot skill distinct slot/intent issue
  modules/basic-skills/src/actions/slot_not_found.js
  modules/basic-skills/src/actions/slot_update_contexts.js
  modules/basic-skills/src/backend/slot.ts
Labels: module/basic-skills

#4747 chore(core): backend restructuration (11)
  src/bp/admin/management/licensing/licensing-router.ts
  src/bp/admin/management/management-router.ts
  src/bp/admin/user/user-router.ts
  src/bp/admin/utils/customAdminRouter.ts
  src/bp/admin/workspace/collaborators/collaborators-router.ts
  src/bp/bpfs.ts
  src/bp/core/app/server.ts
  src/bp/core/migration/index.ts
  src/bp/core/migration/migration-service.ts
  src/bp/core/migration/templates/template_core.ts
  src/bp/core/modules/module-resources-loader.ts
  src/bp/core/routers/bots/index.ts
  src/bp/core/routers/bots/nlu.ts
  src/bp/core/routers/util.ts
  src/bp/core/security/index.ts
  src/bp/core/security/router-security.ts
  src/bp/core/services/ghost/ghost.inversify.ts
  src/bp/core/services/index.ts
  src/bp/core/services/nlu/entities-service.ts
  src/bp/core/services/nlu/intent-service.ts
  src/bp/core/services/nlu/nlu-service.ts
  src/bp/core/user-code/hints/hints-router.ts
  src/bp/migrations/v12_0_0-1560863171-event_collector.ts
  src/bp/migrations/v12_0_0-1560882898-move_users_to_db.ts
  src/bp/migrations/v12_0_0-1560882959-auth_strategies_config.ts
  src/bp/migrations/v12_0_0-1560888466-update_workspaces_content.ts
  src/bp/migrations/v12_10_0-1591119240-migrate_content_in_flow_data_for_ndu_bots.ts
  src/bp/migrations/v12_10_8-1600807697-database_indices.ts
  src/bp/migrations/v12_12_0-1603913437-convert_events_table.ts
  src/bp/migrations/v12_16_3-1611158619-change_dialog_sessions_pk_constraint.ts
  src/bp/migrations/v12_17_1-1611946378-implement_token_version.ts
  src/bp/migrations/v12_17_2-1610388562-change_migration_details_column_to_text.ts
  src/bp/migrations/v12_17_2-1612973566-add_botid_to_dialog_sessions_id_and_remove_botid_column.ts
  src/bp/migrations/v12_18_1-1614560297-change_dialog_sessions_id_column_type.ts
  src/bp/migrations/v12_19_0-1615570996-implement_token_version.ts
  src/bp/migrations/v12_1_0-1564421788-database_srv_logs_table_has_date_timestamp.ts
  src/bp/migrations/v12_1_0-1564683507-remove_migrations_tables.ts
  src/bp/migrations/v12_1_2-1566397053-kvs_fix_primary_keys.ts
  src/bp/migrations/v12_1_3-1567534454-bots_error_handling_flow.ts
  src/bp/migrations/v12_6_0-1581612555-add_hostname_to_logs.ts
  src/bp/migrations/v12_7_1-1583439770-no_repeat_policy.ts
  src/bp/migrations/v12_8_0-1583521821-add_kvs_expiration_column.ts
  src/bp/migrations/v12_8_0-1584383643-action_servers_default_config.ts
Labels: core/backend

#4699 fix(docker): Use UTC time zone
  build/docker/Dockerfile
Labels: infrastructure

#4611 feat(analytics): qna feedback stat
  modules/analytics/src/translations/en.json
  modules/analytics/src/translations/es.json
  modules/analytics/src/translations/fr.json
  modules/analytics/src/views/full/index.tsx
Labels: X-Games

#4736 feat(nlu): Queue trainings on bot mount
  jest.config.js
  modules/nlu/package.json
  modules/nlu/src/backend/api.ts
  modules/nlu/src/backend/application/bot-factory.ts
  modules/nlu/src/backend/application/bot-service.ts
  modules/nlu/src/backend/application/distributed-training-queue.ts
  modules/nlu/src/backend/application/errors.ts
  modules/nlu/src/backend/application/index.ts
  modules/nlu/src/backend/application/pick-seed.test.ts
  modules/nlu/src/backend/application/pick-seed.ts
  modules/nlu/src/backend/application/scoped/bot.ts
  modules/nlu/src/backend/application/scoped/definitions-service.ts
  modules/nlu/src/backend/application/scoped/infrastructure/definitions-repository.ts
  modules/nlu/src/backend/application/scoped/infrastructure/model-repository.ts
  modules/nlu/src/backend/application/scoped/prediction-handler.ts
  modules/nlu/src/backend/application/tests/app-integration.test.ts
  modules/nlu/src/backend/application/tests/app-unit.test.ts
  modules/nlu/src/backend/application/tests/cluster-integration.test.ts
  modules/nlu/src/backend/application/tests/prediction-handler.test.ts
  modules/nlu/src/backend/application/tests/utils/app.u.test.ts
  modules/nlu/src/backend/application/tests/utils/custom-expects.u.test.ts
  modules/nlu/src/backend/application/tests/utils/data.u.test.ts
  modules/nlu/src/backend/application/tests/utils/fake-def-repo.u.test.ts
  modules/nlu/src/backend/application/tests/utils/fake-distributed.u.test.ts
  modules/nlu/src/backend/application/tests/utils/fake-engine.u.test.ts
  modules/nlu/src/backend/application/tests/utils/fake-model-id-service.u.test.ts
  modules/nlu/src/backend/application/tests/utils/fake-model-repo.u.test.ts
  modules/nlu/src/backend/application/tests/utils/fake-training-repo.u.test.ts
  modules/nlu/src/backend/application/tests/utils/mock-extra.u.test.ts
  modules/nlu/src/backend/application/tests/utils/sdk.u.test.ts
  modules/nlu/src/backend/application/tests/utils/stub-logger.u.test.ts
  modules/nlu/src/backend/application/tests/utils/utils.u.test.ts
  modules/nlu/src/backend/application/training-queue.ts
  modules/nlu/src/backend/application/training-repo.ts
  modules/nlu/src/backend/application/typings.ts
  modules/nlu/src/backend/bootstrap.ts
  modules/nlu/src/backend/dialog-conditions/intent-ambiguous.ts
  modules/nlu/src/backend/election/legacy-election.ts
  modules/nlu/src/backend/election/math.test.ts
  modules/nlu/src/backend/election/math.ts
  modules/nlu/src/backend/entities/validation.ts
  modules/nlu/src/backend/index.ts
  modules/nlu/src/backend/middlewares.ts
  modules/nlu/src/backend/module-lifecycle/on-bot-mount.ts
  modules/nlu/src/backend/module-lifecycle/on-bot-unmount.ts
  modules/nlu/src/backend/module-lifecycle/on-server-ready.ts
  modules/nlu/src/backend/module-lifecycle/on-server-started.ts
  modules/nlu/src/backend/train-repo-router.ts
  modules/nlu/src/backend/train-session-service.ts
  modules/nlu/src/backend/typings.ts
  modules/nlu/src/config.ts
  modules/nlu/src/migrations/v12_2_3-1573576448-updated_entities.ts
  modules/nlu/src/migrations/v12_3_2-1577993749-entities_misspelling.ts
  modules/nlu/tsconfig.json
  modules/nlu/yarn.lock
  src/bp/nlu/engine/index.ts
  src/bp/sdk/botpress.d.ts
Labels: module/nlu

#4629 feat(misunderstood): bulk remove
  modules/misunderstood/src/backend/db.test.ts
  modules/misunderstood/src/backend/db.ts
  modules/misunderstood/src/translations/en.json
  modules/misunderstood/src/translations/es.json
  modules/misunderstood/src/translations/fr.json
  modules/misunderstood/src/views/full/MainScreen/NewEventView.tsx
  modules/misunderstood/src/views/full/MainScreen/index.tsx
  modules/misunderstood/src/views/full/SideList.tsx
  modules/misunderstood/src/views/full/SidePanel.tsx
  modules/misunderstood/src/views/full/index.tsx
Labels: X-Games

#4745 feat(nlu): deprecate legacy election
  modules/nlu-testing/src/bot-templates/bp-nlu-regression-testing/latest-results.csv
  modules/nlu-testing/src/bot-templates/bp-nlu-slot-extraction/latest-results.csv
  modules/nlu/src/backend/api.ts
  modules/nlu/src/backend/bootstrap.ts
  modules/nlu/src/backend/election/ambiguous.ts
  modules/nlu/src/backend/election/index.ts
  modules/nlu/src/backend/election/legacy-election.ts
  modules/nlu/src/backend/election/natural-election.ts
  modules/nlu/src/backend/index.ts
  modules/nlu/src/backend/middlewares.ts
  modules/nlu/src/config.ts
  src/bp/nlu/engine/engine/index.ts
  src/bp/nlu/engine/engine/intents/oos-intent-classfier.ts
  src/bp/nlu/engine/engine/intents/oos-intent-classifier.test.ts
  src/bp/nlu/engine/engine/intents/remove-none.test.ts
  src/bp/nlu/engine/index.ts
  src/bp/nlu/engine/typings.ts
  src/bp/nlu/stan/api.ts
  src/bp/nlu/stan/index.ts
  src/bp/nlu/stan/remove-none.test.ts
  src/bp/nlu/stan/remove-none.ts
Labels: core/nlu

#4413 docs(channels): smooch.md update
  docs/guide/docs/channels/smooch.md
Labels: documentation

#4414 docs(channels): telegram.md update
  docs/guide/docs/channels/telegram.md
Labels: documentation

#4752 chore(core): refactor studio backend
  build/package.pkg.json
  modules/ndu/src/backend/migrate.ts
  src/bp/admin/admin-router.ts
  src/bp/core/app/server-utils.ts
  src/bp/core/app/server.ts
  src/bp/core/bots/bots-router.ts
  src/bp/core/bots/index.ts
  src/bp/core/cms/index.ts
  src/bp/core/modules/modules-router.ts
  src/bp/core/routers/bots/index.ts
  src/bp/core/routers/index.ts
  src/bp/core/security/router-security.ts
  src/bp/studio/actions/actions-router.ts
  src/bp/studio/cms/cms-router.ts
  src/bp/studio/flows/flows-router.ts
  src/bp/studio/logs/logs-router.ts
  src/bp/studio/media/media-router.ts
  src/bp/studio/notifications/notifications-router.ts
  src/bp/studio/studio-router.ts
  src/bp/studio/topics/topics-router.ts
  src/bp/studio/utils/api-mapper.ts
  src/bp/studio/utils/custom-studio-router.ts
  src/bp/ui-studio/src/web/actions/api.ts
  src/bp/ui-studio/src/web/actions/index.ts
  src/bp/ui-studio/src/web/views/FlowBuilder/sidePanelTopics/TopicEditor/CreateTopicModal.tsx
  src/bp/ui-studio/src/web/views/FlowBuilder/sidePanelTopics/TopicEditor/EditTopicModal.tsx
  src/bp/ui-studio/src/web/views/FlowBuilder/sidePanelTopics/TopicEditor/import.ts
  src/bp/ui-studio/src/web/views/FlowBuilder/sidePanelTopics/TopicList/index.tsx
  src/bp/ui-studio/src/web/views/FlowBuilder/sidePanelTopics/index.tsx
  src/e2e/studio/flows.test.ts
Labels: core/backend

#4770 fix(admin): check license limits exist before counting nodes
  src/bp/admin/ui/src/management/licensing/index.tsx
Labels: ui/admin

#4517 docs(channels): web.md update
  docs/guide/docs/channels/web.md
Labels: documentation

#4616 feat(misunderstood): group duplicates
  modules/misunderstood/src/backend/api.ts
  modules/misunderstood/src/backend/db.test.ts
  modules/misunderstood/src/backend/db.ts
  modules/misunderstood/src/translations/en.json
  modules/misunderstood/src/translations/es.json
  modules/misunderstood/src/translations/fr.json
  modules/misunderstood/src/views/full/ApiClient.ts
  modules/misunderstood/src/views/full/MainScreen/NewEventView.tsx
  modules/misunderstood/src/views/full/MainScreen/index.tsx
  modules/misunderstood/src/views/full/SideList.tsx
  modules/misunderstood/src/views/full/SidePanel.tsx
  modules/misunderstood/src/views/full/eventUtils.test.ts
  modules/misunderstood/src/views/full/eventUtils.ts
  modules/misunderstood/src/views/full/index.tsx
Labels: X-Games

#4759 fix(studio): check subflow exists before adding its nodes usage
  src/bp/ui-studio/src/web/views/Content/index.tsx
Labels: ui/studio
