Repository botpress/botpress, pull requests merged in 2021-06, with the labels that each got.

#5055 feat(channel-vonage): add support for sending files
  modules/channel-vonage/src/backend/client.ts
  modules/channel-vonage/src/renderers/file.ts
  modules/channel-vonage/src/renderers/index.ts
Labels: module/channel-vonage

#5056 feat(channel-twilio): image reception
  modules/channel-twilio/src/backend/client.ts
  modules/channel-twilio/src/backend/typings.ts
Labels: module/twillio

#5041 fix(studio): moving multiple nodes
  src/bp/ui-studio/src/web/actions/index.ts
  src/bp/ui-studio/src/web/reducers/flows.ts
  src/bp/ui-studio/src/web/views/FlowBuilder/diagram/index.tsx
Labels: ui/studio

#5062 fix(core): fix generating diag report with the pro version
  src/bp/core/app/core-loader.ts
Labels: core/backend

#5052 fix(core): telemetry only on mounted bots
  src/bp/core/telemetry/stats/actions-stats.ts
  src/bp/core/telemetry/stats/configs-stats.ts
  src/bp/core/telemetry/stats/hooks-stats.ts
  src/bp/core/telemetry/stats/legacy-stats.ts
  src/bp/core/telemetry/stats/sdk-stats.ts
Labels: core/backend

#5061 chore(docs): fix missing links in memory topic
  docs/guide/docs/assets/nlu-language-emulator.png
  docs/guide/docs/assets/nlu-language-message.png
  docs/guide/docs/assets/nlu-language-set-variable.png
  docs/guide/docs/assets/slot-extraction-emulator.png
  docs/guide/docs/assets/user-name-message.png
  docs/guide/docs/main/memory.md
Labels: documentation

#5031 chore(docs): deployment tip
  docs/guide/docs/infrastructure/deploying.md
Labels: documentation

#5030 chore(docs): add database tip
  docs/guide/docs/infrastructure/database.md
Labels: documentation

#5023 chore(nlu): upgrade nlu version to 0.0.4
  build/nlu-installer/src/config.ts
  build/nlu-installer/src/installer.ts
  build/nlu-installer/src/typings.ts
  package.json
  src/bp/nlu/index.ts
  src/bp/nlu/typings.ts
Labels: nlu server

#5027 fix(ndu): fix display of intent is trigger editor
  modules/nlu/src/backend/dialog-conditions/intent-is.ts
  src/bp/sdk/botpress.d.ts
  src/bp/ui-studio/src/web/views/FlowBuilder/diagram/TriggerEditor/Condition/Editor.tsx
  src/bp/ui-studio/src/web/views/Nlu/intents/LiteEditor.tsx
Labels: module/ndu

#4977 chore(docs): create features
  docs/guide/docs/assets/tutorials_interbot-diagram.png
  docs/guide/docs/assets/tutorials_interbot-flow.png
  docs/guide/docs/managing/features.md
  docs/guide/website/sidebars.json
Labels: documentation

#5019 chore(docs): rbac fixed links
  docs/guide/docs/managing/rbac.md
Labels: documentation

#4976 chore(docs): create user auth
  docs/guide/docs/managing/user-auth.md
  docs/guide/website/sidebars.json
Labels: documentation

#4975 chore(docs): create single sign on
  docs/guide/docs/assets/oauth/goog_1a_create_oauth2_creds.png
  docs/guide/docs/assets/oauth/goog_1b_create_oauth2_creds.png
  docs/guide/docs/managing/ssotools.md
  docs/guide/website/sidebars.json
Labels: documentation

#4974 chore(docs): update hitl+create hitl next
  docs/guide/docs/assets/hitl-interface.png
  docs/guide/docs/managing/hitl.md
  docs/guide/docs/managing/hitlnext.md
  docs/guide/website/sidebars.json
Labels: documentation

#4969 chore(docs): update internal auth
  docs/guide/docs/assets/auth-methods.png
  docs/guide/docs/managing/authentication.md
Labels: documentation

#5067 chore(dx): exclude some results from quick search
  .vscode/settings.json
Labels: developer experience

#5074 fix(core): fix multiple invalidate
  src/bp/core/dialog/flow/flow-service.ts
Labels: core/backend

#5043 fix(core): better orchestration
  build/downloader/src/cli.ts
  build/package.pkg.json
  modules/nlu/src/backend/bootstrap.ts
  modules/nlu/src/backend/db.ts
  modules/nlu/src/backend/index.ts
  package.json
  src/bp/admin/management/management-router.ts
  src/bp/cluster.ts
  src/bp/core/app/bootstrap.ts
  src/bp/core/app/botpress.ts
  src/bp/core/app/internal-router.ts
  src/bp/core/app/server.ts
  src/bp/core/bots/bot-service.ts
  src/bp/core/bpfs/memory-cache.ts
  src/bp/core/security/auth-service.ts
  src/bp/index.ts
  src/bp/lifecycle.ts
  src/bp/nlu/index.ts
  src/bp/orchestrator/action-server.ts
  src/bp/orchestrator/index.ts
  src/bp/orchestrator/master.ts
  src/bp/orchestrator/nlu-server.ts
  src/bp/orchestrator/studio-client.ts
  src/bp/orchestrator/web-worker.ts
  src/typings/global.d.ts
Labels: core/backend

#4865 chore(docs): update dev pipelines
  docs/guide/docs/advanced/development-pipeline.md
  docs/guide/docs/assets/dev-pipeline.png
  docs/guide/docs/infrastructure/development-pipeline.md
  docs/guide/docs/infrastructure/pipeline.md
Labels: documentation

#5044 fix(nlu): handle disabling the NLU module
  src/bp/core/app/botpress.ts
  src/bp/core/modules/config-reader.ts
Labels: module/nlu

#5089 fix(admin): add missing translation change collaborators role
  src/bp/admin/ui/src/workspace/collaborators/UserList/UserActions.tsx
Labels: ui/admin

#5087 fix(core): fix core migration template import path
  src/bp/core/migration/templates/template_core.ts
Labels: core/backend

#5077 chore(docs): create nlu section
  docs/guide/docs/nlu/3rd-party-NLU.md
  docs/guide/docs/nlu/entity-extraction.md
  docs/guide/docs/nlu/intent-matching.md
  docs/guide/docs/nlu/skill-slot.md
  docs/guide/website/sidebars.json
Labels: documentation

#5076 chore(docs): upload monitoring topic assets
  docs/guide/docs/assets/alerting.png
  docs/guide/docs/assets/monitoring.png
  docs/guide/docs/managing/monitoring.md
Labels: documentation

#5088 fix(core): fix send email skill using teams
  modules/basic-skills/src/actions/send_email.js
Labels: module/basic-skills, module/channel-teams

#5099 chore(docs): update slots documentation
  docs/guide/docs/nlu/skill-slot.md
Labels: documentation

#5100 chore(docs): update 3rd-party-nlu topic
  docs/guide/docs/nlu/3rd-party-NLU.md
Labels: documentation

#5097 chore(docs): update intent documentation
  docs/guide/docs/nlu/intent-matching.md
Labels: documentation

#5092 fix(core): minor fixes for logs and admin
  src/bp/admin/ui/src/app/BottomPanel/Logs/index.tsx
  src/bp/admin/ui/src/app/Menu/index.tsx
  src/bp/core/bots/bot-service.ts
  src/bp/core/logger/persister/console-logger.ts
  src/bp/core/realtime/realtime-service.ts
  src/bp/ui-shared/src/Dropdown/index.tsx
  src/bp/ui-studio/src/web/components/Layout/BottomPanel/Logs/index.tsx
Labels: core/backend

#5101 chore(docs): update internationalization
  docs/guide/docs/nlu/i18n.md
  docs/guide/docs/pro/i18n.md
  docs/guide/website/sidebars.json
Labels: documentation

#5114 chore(docs): all assets for nlu section
  docs/guide/docs/assets/b-i-chat.png
  docs/guide/docs/assets/b-i-interface.png
  docs/guide/docs/assets/custom-entities.png
  docs/guide/docs/assets/entity-input-panel.PNG
  docs/guide/docs/assets/flow-nlu-transition.jpg
  docs/guide/docs/assets/i18n-configs.png
  docs/guide/docs/assets/i18n-missing-translation.png
  docs/guide/docs/assets/i18n-switch-lang.png
  docs/guide/docs/assets/intent-matching-node.png
  docs/guide/docs/assets/intent-matching-qna-conversation.png
  docs/guide/docs/assets/intent-matching-qna-flow.png
  docs/guide/docs/assets/intent-matching-qna-new.png
  docs/guide/docs/assets/intent-matching-slot-conversation.png
  docs/guide/docs/assets/intent-matching-slot-flow.png
  docs/guide/docs/assets/intent-matching-slot-intents.png
  docs/guide/docs/assets/intent-matching-slot-skill.png
  docs/guide/docs/assets/intent-matching-slot-text.png
  docs/guide/docs/assets/intent-matching-switch-case.png
  docs/guide/docs/assets/intent-matching-switch-conversation.png
  docs/guide/docs/assets/intent-matching-switch-intents.png
  docs/guide/docs/assets/intent-matching-transition.png
  docs/guide/docs/assets/nlu-create-entity.png
  docs/guide/docs/assets/nlu-create-slot.png
  docs/guide/docs/assets/nlu-intent.png
  docs/guide/docs/assets/nlu-intents-submenu.png
  docs/guide/docs/assets/nlu-list-entity.png
  docs/guide/docs/assets/nlu-overview.png
  docs/guide/docs/assets/nlu-pattern-entity.png
  docs/guide/docs/assets/nlu-tag-slot.png
  docs/guide/docs/assets/slot-skill-flow.png
  docs/guide/docs/assets/slot-skill-intents.png
  docs/guide/docs/assets/slot-skill-outcomes.png
Labels: documentation

#5102 feat(core): Config to toggle public converse
  src/bp/core/bots/bots-router.ts
  src/bp/core/config/bot.config.ts
  src/bp/core/converse/converse-router.ts
  src/bp/sdk/botpress.d.ts
  src/e2e/admin/bots.test.ts
  src/e2e/utils.ts
Labels: core/converse

#5080 feat(nlu): upgrade NLU version + bring back nlu debug logs
  package.json
  src/bp/core/app/botpress.ts
  src/bp/index.ts
  src/bp/nlu/index.ts
  src/bp/nlu/typings.ts
Labels: nlu server

#5093 fix(nlu): spellcheck logic is more natural
  modules/nlu/src/backend/api.ts
  modules/nlu/src/backend/application/scoped/prediction-handler.ts
  modules/nlu/src/backend/application/typings.ts
  modules/nlu/src/backend/election/most-confident.ts
  modules/nlu/src/backend/election/natural-election.ts
  modules/nlu/src/backend/election/spellcheck-handler.ts
  modules/nlu/src/backend/middlewares.ts
  src/bp/nlu/index.ts
Labels: core/nlu

#5091 fix(docs):migrate azure oauth to sso & minor fix
  docs/guide/docs/managing/authentication.md
  docs/guide/docs/managing/ssotools.md
Labels: documentation

#5123 fix(studio): fix icon display in the studio and skill
  examples/custom-component/src/backend/index.ts
  examples/module-templates/basic-module/src/backend/index.ts
  examples/module-templates/complete-module/src/backend/index.ts
  examples/proactive/src/backend/index.ts
  modules/basic-skills/src/backend/index.ts
  modules/bot-improvement/src/backend/index.ts
  modules/broadcast/src/backend/index.ts
  modules/channel-slack/src/backend/index.ts
  modules/channel-smooch/src/backend/index.ts
  modules/channel-teams/src/backend/index.ts
  modules/channel-telegram/src/backend/index.ts
  modules/channel-twilio/src/backend/index.ts
  modules/channel-vonage/src/backend/index.ts
  modules/channel-web/src/backend/index.ts
  modules/examples/src/backend/index.ts
  modules/extensions/src/backend/index.ts
  modules/google-speech/src/backend/index.ts
  modules/hitl/src/backend/index.ts
  modules/ndu/src/backend/index.ts
  modules/uipath/src/backend/index.ts
Labels: module/basic-skills, ui/studio

#5127 fix(docs): links & minor kinks
  docs/guide/docs/assets/intent-creation.png
  docs/guide/docs/managing/rbac.md
Labels: documentation

#5130 fix(teams): send quick_reply for Choice skill
  modules/channel-teams/src/backend/client.ts
  modules/channel-teams/src/renderers/choices.ts
Labels: bug, module/channel-teams

#5117 chore(docs): local dev tips for Custom Modules
  docs/guide/docs/advanced/custom-module.md
Labels: documentation

#5135 chore(core): add more content to diag
  src/bp/core/distributed/redis.ts
  src/bp/diag/index.ts
  src/bp/diag/utils.ts
  src/bp/orchestrator/studio-client.ts
Labels: core/dialog

#5152 chore(docs): channel web fix links
  docs/guide/docs/channels/web.md
Labels: documentation

#5148 fix(hitl-next): show new live messages only from the current chat
  modules/hitlnext/src/views/full/app/components/ConversationHistory.tsx
Labels: module/hitlnext(beta)

#5131 feat(builtin): improve single choice
  modules/builtin/src/content-types/_base.js
  modules/builtin/src/content-types/single_choice.js
  modules/builtin/src/content-types/text.js
  modules/builtin/src/translations/en.json
  modules/builtin/src/translations/es.json
  modules/builtin/src/translations/fr.json
  modules/extensions/src/content-types/_base.js
  modules/extensions/src/content-types/dropdown.js
  package.json
  src/bp/ui-shared/src/typings.d.ts
Labels: module/basic-skills
