Repository botpress/botpress, pull requests merged in 2021-08, with the labels that each got.

#5232 chore(docs): create integrating external services section
  docs/guide/docs/integrating/existing-backend.md
  docs/guide/docs/integrating/external-api.md
  docs/guide/docs/integrating/skill-call-api.md
  docs/guide/docs/integrating/uipath.md
  docs/guide/website/sidebars.json
Labels: documentation

#5231 docs: minor changes to building chatbot section
  docs/guide/docs/assets/event_enginev2.2.png
  docs/guide/docs/assets/hld.png
  docs/guide/docs/assets/nlu-language-raw-expression.png
  docs/guide/docs/assets/qna-overview.png
  docs/guide/docs/main/memory.md
  docs/guide/docs/main/module.md
  docs/guide/docs/main/nlu.md
  docs/guide/docs/main/overview2.md
  docs/guide/docs/main/qna-module.md
  docs/guide/website/sidebars.json
Labels: documentation

#5239 feat(messaging): added webhook support when using an external messaging
  packages/bp/src/core/messaging/messaging-client.ts
  packages/bp/src/core/messaging/messaging-router.ts
  packages/bp/src/core/messaging/messaging-service.ts
Labels: module/unified-messaging

#5238 feat(common): add roles to workspace creation API
  packages/bp/src/admin/workspace/workspaces/workspaces-router.ts
  packages/bp/src/common/typings.ts
  packages/bp/src/common/validation.ts
  packages/bp/src/core/users/workspace-service.ts
Labels: core/security

#5223 feat(core): add authStrategy to workspace creation
  packages/bp/src/common/defaults.ts
  packages/bp/src/common/typings.ts
  packages/bp/src/common/validation.ts
  packages/bp/src/core/users/workspace-service.ts
Labels: core/security

#5241 feat(messaging): added webhook validation
  packages/bp/src/core/messaging/messaging-router.ts
Labels: module/unified-messaging

#5248 fix(hitlnext): fix piping of events
  modules/hitlnext/src/backend/middleware.ts
Labels: module/hitlnext(beta)

#5237 feat(messaging): allow to use an external messaging server
  packages/bp/src/core/app/botpress.ts
  packages/bp/src/core/messaging/legacy.ts
  packages/bp/src/core/messaging/messaging-client.ts
  packages/bp/src/core/messaging/messaging-router.ts
  packages/bp/src/core/messaging/messaging-service.ts
  packages/bp/src/orchestrator/messaging-server.ts
  packages/bp/src/orchestrator/web-worker.ts
  packages/bp/src/typings/global.d.ts
Labels: module/unified-messaging

#5222 chore(dev): benchmark using web instead of converse
  packages/bp/src/bench/index.ts
  packages/bp/src/index.ts
  packages/bp/src/orchestrator/nlu-server.ts
  packages/bp/src/orchestrator/studio-client.ts
Labels: core/backend

#5247 chore(ci_cd): Removed unnecessary code. Modified if statement for the dockerhub push
  .github/workflows/docker.yml
Labels: infrastructure

#5266 fix(messaging): legacy route send ext url in headers
  packages/bp/src/core/messaging/legacy.ts
Labels: module/unified-messaging

#5251 feat(channel-web): add RTL support in webchat
  modules/channel-web/assets/default-emulator.css
  modules/channel-web/assets/default.css
  modules/channel-web/src/views/lite/components/Composer.tsx
  modules/channel-web/src/views/lite/components/Container.tsx
  modules/channel-web/src/views/lite/components/common/BotInfo.tsx
  modules/channel-web/src/views/lite/components/messages/MessageList.tsx
  modules/channel-web/src/views/lite/store/index.ts
  modules/channel-web/src/views/lite/translations/ar.json
  modules/channel-web/src/views/lite/translations/en.json
  modules/channel-web/src/views/lite/translations/fr.json
  modules/channel-web/src/views/lite/utils.tsx
Labels: module/channel-web

#5268 feat(channel-web): RTL support for non-text content types
  modules/builtin/src/content-types/single_choice.js
  modules/channel-web/assets/default-emulator.css
  modules/channel-web/assets/default.css
  modules/extensions/src/content-types/dropdown.js
  modules/extensions/src/views/lite/components/Dropdown.jsx
Labels: module/channel-web

#5283 fix(messaging): filter module errors for channels
  packages/bp/src/core/app/bootstrap.ts
Labels: module/unified-messaging

#5275 fix(ci_cd): Modified if on the dockerhub connection
  .github/workflows/docker.yml
Labels: infrastructure

#5306 chore(doc): updated the main channels doc to point to the proper pages
  docs/guide/docs/main/channels.md
Labels: documentation

#5265 feat(core): filter /listAvailableUsers on roles
  packages/bp/src/admin/workspace/collaborators/collaborators-router.ts
Labels: core/security

#5187 fix(studio): move bot migrations to studio
  modules/builtin/src/migrations/v12_5_0-1577776334-text-markdown.ts
  modules/nlu/src/migrations/v12_0_1-1562193005-migrate_numeral_entities_to_number.ts
  modules/nlu/src/migrations/v12_2_3-1573576448-updated_entities.ts
  modules/nlu/src/migrations/v12_3_2-1577993749-entities_misspelling.ts
  modules/nlu/src/migrations/v12_7_1-1583507028-prune_and_compress_models.ts
  package.json
  packages/bp/src/core/bots/bot-service.ts
  packages/bp/src/core/migration/bot-migration-service.ts
  packages/bp/src/core/migration/index.ts
  packages/bp/src/core/migration/migration-service.ts
  packages/bp/src/migrations/v12_10_0-1591119240-migrate_content_in_flow_data_for_ndu_bots.ts
  packages/bp/src/migrations/v12_1_3-1567534454-bots_error_handling_flow.ts
  packages/bp/src/migrations/v12_21_1-1618260400-bot_content_type_update.ts
  packages/bp/src/migrations/v12_22_1-1621260400-add_file_and_location_content_type_bot_config.ts
  packages/bp/src/migrations/v12_8_0-1583933939-qna_multi_contexts.ts
  packages/bp/src/orchestrator/studio-client.ts
Labels: ui/studio

#5235 docs(skill-email): Added section for the transportString Connection
  docs/guide/docs/assets/tutorials/transportConnectionString.png
  docs/guide/docs/tutorials/skill-email.md
Labels: documentation

#5207 docs(nlu): Add warnings to docker-compose example
  examples/docker-compose/docker-compose-standalone-nlu.yaml
Labels: documentation

#5319 feat(core): bot-scoped libraries
  modules/code-editor/src/backend/definitions.ts
  modules/code-editor/src/backend/editor.ts
  modules/code-editor/src/translations/en.json
  modules/code-editor/src/views/full/SidePanel.tsx
  modules/libraries/src/backend/index.ts
  package.json
  packages/bp/src/core/bots/bot-service.ts
  packages/bp/src/core/bpfs/cache-invalidators.ts
  packages/bp/src/core/bpfs/ghost-service.ts
  packages/bp/src/core/user-code/action-service.ts
  packages/bp/src/core/user-code/hook-service.ts
  packages/bp/src/core/user-code/utils.ts
Labels: module/shared-libraries

#5301 fix(core): merge extensions in channel-web
  modules/builtin/src/content-types/dropdown.js
  modules/builtin/src/translations/en.json
  modules/builtin/src/translations/es.json
  modules/builtin/src/translations/fr.json
  modules/channel-web/assets/default-emulator.css
  modules/channel-web/package.json
  modules/channel-web/src/backend/socket.ts
  modules/channel-web/src/views/full/index.tsx
  modules/channel-web/src/views/lite/components/ContextMenu.tsx
  modules/channel-web/src/views/lite/components/Keyboard.tsx
  modules/channel-web/src/views/lite/components/messages/Message.tsx
  modules/channel-web/src/views/lite/components/messages/renderer/Dropdown.tsx
  modules/channel-web/src/views/lite/main.tsx
  modules/channel-web/src/views/lite/store/index.ts
  modules/channel-web/src/views/lite/typings.d.ts
  modules/channel-web/yarn.lock
  modules/extensions/.gitignore
  modules/extensions/package.json
  modules/extensions/src/backend/index.ts
  modules/extensions/src/config.ts
  modules/extensions/src/content-types/_base.js
  modules/extensions/src/content-types/_utils.js
  modules/extensions/src/translations/en.json
  modules/extensions/src/translations/es.json
  modules/extensions/src/translations/fr.json
  modules/extensions/src/views/declaration.d.ts
  modules/extensions/src/views/full/index.jsx
  modules/extensions/src/views/lang.ts
  modules/extensions/src/views/lite/components/Dropdown.jsx
  modules/extensions/src/views/lite/components/debugger/Wrapper.tsx
  modules/extensions/src/views/lite/components/debugger/index.tsx
  modules/extensions/src/views/lite/components/debugger/style.scss
  modules/extensions/src/views/lite/components/debugger/style.scss.d.ts
  modules/extensions/src/views/lite/index.jsx
  modules/extensions/src/views/lite/utils.tsx
  modules/extensions/src/views/tsconfig.json
  modules/extensions/tsconfig.json
  modules/extensions/yarn.lock
  package.json
  packages/bp/src/common/defaults.ts
  packages/bp/src/core/app/server.ts
  packages/bp/src/core/bots/bots-router.ts
  packages/bp/src/core/config/config-loader.ts
Labels: module/channel-web

#5308 chore(doc): added proactive messages doc for teams
  docs/guide/docs/channels/teams.md
Labels: documentation

#5296 feat(nlu): nlu cloud configuration
  modules/nlu/package.json
  modules/nlu/src/backend/application/bot-factory.ts
  modules/nlu/src/backend/application/index.ts
  modules/nlu/src/backend/application/scoped/bot.ts
  modules/nlu/src/backend/application/typings.ts
  modules/nlu/src/backend/bootstrap.ts
  modules/nlu/src/backend/cloud/cache.ts
  modules/nlu/src/backend/cloud/client.ts
  modules/nlu/src/backend/cloud/lock.test.ts
  modules/nlu/src/backend/cloud/lock.ts
  modules/nlu/src/backend/cloud/oauth.ts
  modules/nlu/yarn.lock
  packages/bp/src/sdk/botpress.d.ts
Labels: nlu server

#5285 fix(admin): add the chatuser role id to the filter
  packages/bp/src/admin/ui/src/workspace/collaborators/UserList/index.tsx
  packages/bp/src/admin/workspace/roles/roles-router.ts
Labels: bug

#5205 feat(hitlnext): add feature to filter handoffs list by tags
  modules/hitlnext/src/views/full/App.tsx
  modules/hitlnext/src/views/full/app/components/HandoffItem.tsx
  modules/hitlnext/src/views/full/app/components/HandoffList.tsx
  modules/hitlnext/src/views/full/app/components/HandoffListHeader.tsx
  modules/hitlnext/src/views/full/style.scss
  modules/hitlnext/src/views/full/style.scss.d.ts
Labels: module/hitlnext(beta)

#5166 feat(messaging): 4.5 - frontend rendering
  modules/bot-improvement/src/views/full/components/messages/MessageList.tsx
  modules/builtin/src/content-types/_utils.js
  modules/builtin/src/content-types/audio.js
  modules/builtin/src/content-types/card.js
  modules/builtin/src/content-types/carousel.js
  modules/builtin/src/content-types/dropdown.js
  modules/builtin/src/content-types/file.js
  modules/builtin/src/content-types/image.js
  modules/builtin/src/content-types/location.js
  modules/builtin/src/content-types/single_choice.js
  modules/builtin/src/content-types/text.js
  modules/builtin/src/content-types/video.js
  modules/channel-web/src/hooks/before_outgoing_middleware/quick_replies.js
  modules/channel-web/src/views/lite/components/messages/MessageGroup.tsx
  modules/hitl/src/views/full/components/messages/MessageList.tsx
  packages/bp/src/core/cms/render-service.test.ts
  packages/bp/src/core/cms/render-service.ts
  packages/bp/src/core/events/event-engine.ts
  packages/bp/src/sdk/botpress.d.ts
  packages/ui-shared-lite/Payloads/index.ts
  packages/ui-shared/src/index.tsx
  packages/ui-shared/src/typings.d.ts
Labels: module/unified-messaging

#5183 fix(messaging): 6 - fix debugger
  modules/channel-web/src/backend/api.ts
  modules/channel-web/src/backend/db.ts
  modules/channel-web/src/backend/socket.ts
  modules/channel-web/src/views/lite/components/messages/InlineFeedback.tsx
  modules/channel-web/src/views/lite/components/messages/Message.tsx
  modules/channel-web/src/views/lite/components/messages/MessageGroup.tsx
  modules/channel-web/src/views/lite/core/api.tsx
  modules/channel-web/src/views/lite/store/index.ts
  modules/channel-web/src/views/lite/typings.d.ts
  packages/bp/src/core/bots/bots-router.ts
  packages/bp/src/core/events/event-collector.ts
  packages/bp/src/core/events/event-engine.ts
  packages/bp/src/core/events/event-sdk-impl.ts
  packages/bp/src/core/events/event-table.ts
  packages/bp/src/core/messaging/index.ts
  packages/bp/src/core/messaging/messaging-bot-router.ts
  packages/bp/src/core/messaging/messaging-router.ts
  packages/bp/src/core/messaging/messaging-service.ts
  packages/bp/src/migrations/v12_26_0-1629781900-add_messageid_column_to_events.ts
  packages/bp/src/sdk/botpress.d.ts
Labels: module/unified-messaging

#5344 chore(devops): Modified docker-compose-* example
  examples/docker-compose/docker-compose-community-nginx.yaml
  examples/docker-compose/docker-compose-community.yaml
  examples/docker-compose/docker-compose-pro-nginx.yaml
  examples/docker-compose/docker-compose-pro.yaml
  examples/docker-compose/docker-compose-standalone-nlu.yaml
  examples/docker-compose/nginx/nginx.conf
Labels: infrastructure

#5360 docs(infra): Added Bash code in to bullet point
  docs/guide/docs/infrastructure/deploying.md
Labels: documentation

#5357 chore(docs): SDK page fixes, docs sitemaps
  build/docs/typeDocTheme/layouts/default.hbs
  build/gulp.docs.js
  docs/guide/website/package.json
  docs/guide/website/sitemap.js
  docs/guide/website/yarn.lock
  package.json
Labels: documentation

#5368 fix(admin): change pipeline stage edit endpoint
  packages/bp/src/admin/ui/src/workspace/bots/EditStageModal.tsx
Labels: core/pipeline

#5371 chore(core): create test bed for hitlnext, analytics, and misunderstood
  jest.config.js
  modules/analytics/src/backend/analytics-unit.test.ts
  modules/analytics/src/backend/db.test.ts
  modules/analytics/src/backend/db.ts
  modules/hitl/src/backend/db.test.ts
  modules/hitl/src/backend/db.ts
  modules/hitl/src/backend/hitl-unit.test.ts
  modules/hitlnext/src/backend/hitlnext-unit.test.ts
  modules/hitlnext/src/backend/repository.test.ts
  modules/misunderstood/src/backend/db.test.ts
  package.json
  packages/bp/jest.config.js
  packages/bp/package.json
  packages/bp/src/jest-before.ts
Labels: module/analytics, module/misunderstood, module/hitlnext(beta)

#5348 chore(dev): merge dependabot suggestions
  build/module-builder/package.json
  build/module-builder/yarn.lock
  docs/guide/website/yarn.lock
  modules/.scheduler/yarn.lock
  modules/nlu/package.json
  modules/nlu/yarn.lock
  package.json
  packages/bp/package.json
  yarn.lock
Labels: dependencies

#5333 chore(docs): update uipath
  docs/guide/docs/integrating/uipath.md
Labels: documentation

#5332 chore(docs): update call api skill
  docs/guide/docs/integrating/skill-call-api.md
Labels: documentation

#5331 chore(docs): update action api
  docs/guide/docs/integrating/external-api.md
Labels: documentation

#5320 chore(docs): external services
  docs/guide/docs/integrating/existing-backend.md
  docs/guide/website/sidebars.json
Labels: documentation

#5177 docs(main): update memory
  docs/guide/docs/assets/access-debugger.png
  docs/guide/docs/assets/flow-memory-action.png
  docs/guide/docs/assets/nlu-emulator.png
  docs/guide/docs/assets/nlu-raw-expression.png
  docs/guide/docs/assets/nlu-variable.png
  docs/guide/docs/main/memory.md
Labels: documentation

#5372 feat(misunderstood): add markdown by default for misunderstood chatPreview
  modules/misunderstood/src/views/full/MainScreen/ChatPreview.tsx
  modules/misunderstood/src/views/lite/utils.tsx
Labels: module/misunderstood

#5379 chore(messaging): bump messaging to v0.1.11
  package.json
Labels: module/unified-messaging

#5375 fix(channel-web): fix missing dependencies
  modules/channel-web/package.json
  modules/channel-web/yarn.lock
Labels: module/channel-web
