Repository botpress/botpress, pull requests merged in 2022-01, with the labels that each got.

#11211 chore(ci_cd): use gh-actions v1
  .github/workflows/branch-deleted.yml
  .github/workflows/publish-binaries.yml
Labels: infrastructure

#11216 chore(ci_cd): added action to create pre-release
  .github/workflows/create-pre-release.yml
Labels: infrastructure

#11210 chore(ci_cd): added action to create release pull request
  .github/workflows/create-pre-release.yml
  .github/workflows/create-release-pr.yml
  build/gulp.package.js
  build/package.json
  build/update_pkg_version.js
  release-version.sh
Labels: infrastructure

#5519 chore(e2e): improve e2e tests
  .eslintrc.js
  .github/workflows/tests.yml
  jest.config.js
  jest.e2e.config.ts
  jest.integration.config.ts
  jest.unit.config.ts
  package.json
  packages/bp/e2e/README.md
  packages/bp/e2e/admin/auth.test.ts
  packages/bp/e2e/admin/bots.test.ts
  packages/bp/e2e/admin/login.test.ts
  packages/bp/e2e/admin/logout.test.ts
  packages/bp/e2e/admin/ui.test.ts
  packages/bp/e2e/admin/users.test.ts
  packages/bp/e2e/all.test.ts
  packages/bp/e2e/assets/auth-config.json
  packages/bp/e2e/assets/auth-config.ts
  packages/bp/e2e/assets/config.ts
  packages/bp/e2e/customEnvironment.js
  packages/bp/e2e/jest-puppeteer.config.js
  packages/bp/e2e/jest.environment.ts
  packages/bp/e2e/jest.setup.ts
  packages/bp/e2e/modules/code-editor.test.ts
  packages/bp/e2e/modules/testing.test.ts
  packages/bp/e2e/modules/webchat.test.ts
  packages/bp/e2e/studio/cms.test.ts
  packages/bp/e2e/studio/flows.test.ts
  packages/bp/e2e/studio/nlu.test.ts
  packages/bp/e2e/studio/qna.test.ts
  packages/bp/e2e/studio/ui.test.ts
  packages/bp/e2e/tsconfig.json
  packages/bp/e2e/utils.ts
  packages/bp/e2e/utils/expectPuppeteer.ts
  packages/bp/e2e/utils/index.ts
  packages/bp/jest.e2e.config.js
  packages/bp/jest.setup.js
  packages/bp/package.json
  packages/bp/src/core/bpfs/drivers/db-driver.integration.test.ts
  packages/bp/src/core/kvs/kvs.integration.test.ts
  packages/bp/src/jest-resolver.js
  packages/bp/tsconfig.json
  packages/bp/tsconfig.test.json
  packages/ui-admin/src/workspace/collaborators/UserList/User.tsx
  packages/ui-shared-lite/utils/global.d.ts
  packages/ui-shared-lite/utils/storage.test.ts
  yarn.lock
Labels: infrastructure

#11224 chore(ci_cd): create draft release instead of pre release
  .github/workflows/create-draft-release.yml
Labels: infrastructure

#11244 chore(deps): update dependencies
  modules/basic-skills/package.json
  modules/basic-skills/yarn.lock
  modules/bot-improvement/package.json
  modules/bot-improvement/yarn.lock
  modules/broadcast/package.json
  modules/broadcast/yarn.lock
  yarn.lock
Labels: dependencies

#11265 chore(migrations): fix old migration wrong version
  packages/bp/src/migrations/v12_24_0-1626065192-messaging-database.ts
Labels: master

#11204 chore: notify slack channel for new discussion post
  .github/workflows/slack-notify.yml
Labels: master

#11248 fix(admin): update branding assets
  packages/ui-admin/public/favicon.ico
  packages/ui-admin/src/app/Menu/logo-icon.svg
  packages/ui-admin/src/app/media/logo_white.png
  packages/ui-lite/src/index.html
Labels: master

#11202 feat(admin): added net promoter score in botpress
  packages/ui-admin/src/app/NetPromoterScore/NetPromotingScore/NPS.tsx
  packages/ui-admin/src/app/NetPromoterScore/NetPromotingScore/SegmentHandler.tsx
  packages/ui-admin/src/app/NetPromoterScore/NetPromotingScore/components/NPSAdditionComment/NPSModal.tsx
  packages/ui-admin/src/app/NetPromoterScore/NetPromotingScore/components/NPSAdditionComment/index.tsx
  packages/ui-admin/src/app/NetPromoterScore/NetPromotingScore/components/NPSAdditionComment/style.scss
  packages/ui-admin/src/app/NetPromoterScore/NetPromotingScore/components/NPSAdditionComment/style.scss.d.ts
  packages/ui-admin/src/app/NetPromoterScore/NetPromotingScore/components/NPSScale/index.tsx
  packages/ui-admin/src/app/NetPromoterScore/NetPromotingScore/components/NPSScale/style.scss
  packages/ui-admin/src/app/NetPromoterScore/NetPromotingScore/components/NPSScale/style.scss.d.ts
  packages/ui-admin/src/app/NetPromoterScore/NetPromotingScore/index.tsx
  packages/ui-admin/src/app/NetPromoterScore/NetPromotingScore/style.scss
  packages/ui-admin/src/app/NetPromoterScore/NetPromotingScore/style.scss.d.ts
  packages/ui-admin/src/app/NetPromoterScore/promotingScore.tsx
  packages/ui-admin/src/app/routes/index.tsx
  packages/ui-admin/src/app/translations/en.json
  packages/ui-admin/src/app/translations/fr.json
Labels: master

#11288 fix(channel-web): fetch last message for each convo
  modules/channel-web/src/backend/api.ts
Labels: master

#11291 chore(messaging): bump to 1.0.0
  .github/workflows/code/check-pr/index.js
  modules/channel-web/package.json
  modules/channel-web/yarn.lock
  modules/hitl/package.json
  modules/hitl/yarn.lock
  modules/hitlnext/package.json
  modules/hitlnext/yarn.lock
  modules/misunderstood/package.json
  modules/misunderstood/yarn.lock
  package.json
  yarn.lock
Labels: master

#11325 chore(messaging): bump messaging
  package.json
Labels: master

#5761 chore(dialog): detect infinite loop even when transition to error flow
  packages/bp/src/core/dialog/dialog-engine.ts
  packages/bp/src/core/dialog/errors.ts
Labels: master
